sudo: false
distro: xenial

language: python

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8

install:
  - python -m pip install --upgrade pip setuptools
  - python -m pip install --upgrade codecov
  - python -m pip install --force-reinstall -r requirements.txt
  - python -m pip install --force-reinstall -r requirements-tests.txt
  - python -m pip install -e .

script:
  - pytest
  - python -m doctest README.md

after_success:
  - python -m codecov -f coverage.xml -X gcov

deploy:
  provider: pypi
  user: __token__
  password:
    secure: dFv1Ro2yYaUe1rui095swH8577anwkY/NBlQ0S7YuLImKunHIFLzn1oKQ1GT9xcn+4A0zAK9qx0vE7Wa1yDSFeful3fDqEgLDxwqaio3gqbbcHP9gm0dmHR3dSGUtz5r2015al4rDD8yEPfSZLOQBRsHnnQloinJOlrtnO4PySD0MmeCICV8GT+DEXxa61dosoam75R8FmA1DSYraf0T75aEIF6faxMABC3LWxIaK/AZGsOrDVmOS8MEdvu8DK19fvzXy9GTIdIONFd0e1s2P4EmTz2wO85qCJA9byw66SrOCwpN8dnS0EoV7Ml7+yVGH/wAS0ZxGo6kmpvSGE1+ASzu2qaWitry6os/3aMLaQncxQeDAghM1KQo19wjxw+4sB97+TG6uv2lNq9xcro0yv1qU+cxeMlzP1NP6CJyY7iiEI0eG523gCEg+vMy2Y8Bvs25YzJ84t18eF+6TQBF4QsgvN+f9BRpDLB2RgcKAi+AVQlddI7YKpOp8fjRBmjqtkxoWY3EffvSDY6I3wO4Nfu9964+NwsF5zGU7RS2rqmgWCH8bjoD4AZla7dyozBnFKBC0u+vRhxVa3E04nKfT7d713e3XJJytQAwjv2PckS96lyQWymPOJD9uRGAq++EKBShisTnEme2G7r0seF2S0BbkfseXpC01vYlj550hTA=
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    branch: master
