version: '3'

services:
  martinez-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/martinez-pypy:0.6.0-alpha
    volumes:
      - ./martinez/:/opt/martinez/martinez/
      - ./pytest.ini:/opt/martinez/pytest.ini
      - ./README.md:/opt/martinez/README.md
      - ./requirements-tests.txt:/opt/martinez/requirements-tests.txt
      - ./requirements.txt:/opt/martinez/requirements.txt
      - ./setup.py:/opt/martinez/setup.py
      - ./tests/:/opt/martinez/tests/
    entrypoint: pytest
